package demo.d2.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d2.KertomaWhile.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.01.20 15:04:53 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KertomaWhileTest {



  // Generated by ComTest BEGIN
  /** testKertoma18 */
  @Test
  public void testKertoma18() {    // KertomaWhile: 18
    assertEquals("From: KertomaWhile line: 19", 6, kertoma(3)); 
    assertEquals("From: KertomaWhile line: 20", 120, kertoma(5)); 
    assertEquals("From: KertomaWhile line: 21", 1, kertoma(0)); 
  } // Generated by ComTest END
}