package dynaaminen.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import dynaaminen.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.16 20:32:36 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TaulukkoGenTest {



  // Generated by ComTest BEGIN
  /** 
   * testTaulukkoGen11 
   * @throws TaulukkoGen.TaulukkoTaysiException when error
   */
  @Test
  public void testTaulukkoGen11() throws TaulukkoGen.TaulukkoTaysiException {    // TaulukkoGen: 11
    TaulukkoGen<Integer> luvut = new TaulukkoGen<Integer>(); 
    Integer oma = new Integer(7); 
    luvut.lisaa(0); luvut.lisaa(2); 
    luvut.lisaa(99);  // Tekee oikeasti luvut.lisaa(new Integer(99));
    luvut.lisaa(oma); 
    assertEquals("From: TaulukkoGen line: 18", "0,2,99,7", luvut.toString()); 
    luvut.set(1,4); 
    luvut.set(3,88); 
    oma = luvut.get(3); 
    assertEquals("From: TaulukkoGen line: 22", "0,4,99,88", luvut.toString()); 
    int luku = luvut.get(2);  // oik: luku = (Integer)(luvut.get(2)).intValue();
    assertEquals("From: TaulukkoGen line: 24", 99, luku); 
    luvut.lisaa(4); 
    luvut.lisaa(4); 
    TaulukkoGen<String> sanat = new TaulukkoGen<String>(); 
    sanat.lisaa("kissa"); 
    sanat.lisaa("koira"); 
    assertEquals("From: TaulukkoGen line: 31", "kissa,koira", sanat.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa72 */
  @Test
  public void testLisaa72() {    // TaulukkoGen: 72
    TaulukkoGen<Integer> luvut = new TaulukkoGen<Integer>(); 
    luvut.lisaa(1); 
    luvut.lisaa(2); 
    luvut.lisaa(3); 
    luvut.lisaa(4); 
    luvut.lisaa(5); 
    luvut.lisaa(6); 
    assertEquals("From: TaulukkoGen line: 80", "1,2,3,4,5,6", luvut.toString());
  } // Generated by ComTest END
}