package demo.d11.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d11.FunktionMinimi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.29 15:53:43 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class FunktionMinimiTest {



  // Generated by ComTest BEGIN
  /** testFunMin77 */
  @Test
  public void testFunMin77() {    // FunktionMinimi: 77
    assertEquals("From: FunktionMinimi line: 79", -10, funMin(new P2(0,1,0), -10, 10, 1000), 0.000001);  // Testataan että alkupisteessä oleva minimi löytyy
    assertEquals("From: FunktionMinimi line: 80", 0, funMin(new P2(1,0,0), -10, 10, 1000), 0.000001);  // Testataan että väliltä löytyvä minimi löytyy
    assertEquals("From: FunktionMinimi line: 81", 1, funMin(new P2(1,0,1), -10, 10, 1000), 0.000001);  // Testataan että minimi muuttuu kun vakiotermin verran
    assertEquals("From: FunktionMinimi line: 82", -9999, funMin(new P2(-1,0,1), -10, 100, 1000), 0.000001);  // Testataan, että päätepisteessä oleva minimi löytyy
    assertEquals("From: FunktionMinimi line: 83", -1, funMin(new SinFun(), -2, 2, 1000), 0.000001);  // Testataan jollakin toisentyyppisellä funktiolla
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testFunMax103 */
  @Test
  public void testFunMax103() {    // FunktionMinimi: 103
    assertEquals("From: FunktionMinimi line: 105", 10, funMax(new P2(0,-1,0), -10, 10, 1000), 0.000001);  // Testataan että alkupisteessä oleva maksimi löytyy
    assertEquals("From: FunktionMinimi line: 106", 0, funMax(new P2(-1,0,0), -10, 10, 1000), 0.000001);  // Testataan että väliltä löytyvä maksimi löytyy
    assertEquals("From: FunktionMinimi line: 107", 1, funMax(new P2(-1,0,1), -10, 10, 1000), 0.000001);  // Testataan että maksimi muuttuu vakiotermin verran
    assertEquals("From: FunktionMinimi line: 108", 10001, funMax(new P2(1,0,1), -10, 100, 1000), 0.000001);  // Testataan, että päätepisteessä oleva maksimi löytyy
    assertEquals("From: FunktionMinimi line: 109", 1, funMax(new SinFun(), -2, 2, 1000), 0.000001);  // Testataan jollakin toisentyyppisellä funktiolla
  } // Generated by ComTest END
}