package demo.d11.test;
// Generated by ComTest BEGIN
import fi.jyu.mit.ohj2.Suuntaaja;
import demo.d11.FunktionMinimi.*;
import demo.d11.FunktionMinimi;
import demo.d11.FunktionMinimi.FunktioRR;
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d11.Sin.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.29 15:14:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SinTest {



  // Generated by ComTest BEGIN
  /** testPiirra46 */
  @Test
  public void testPiirra46() {    // Sin: 46
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    double x1=-5,x2=5,dx=0.5,y1,y2; 
    FunktioRR f = new SinFun(); 
    y1 = FunktionMinimi.funMin(f,x1,x2,(x2-x1)/dx); 
    y2 = FunktionMinimi.funMax(f,x1,x2,(x2-x1)/dx); 
    piirra(f,x1,x2,y1,y2,dx); 
    String tulos =
    "                                       *\n" +
    "                                       *\n" +
    "                                   *\n"     +
    "                           *\n" +
    "                 *\n" +
    "        *\n" +
    "  *\n" +
    "*\n" +
    "   *\n" +
    "          *\n" +
    "                    *\n" +
    "                              *\n" +
    "                                     *\n" +
    "                                       *\n" +
    "                                      *\n" +
    "                                *\n" +
    "                       *\n" +
    "             *\n" +
    "     *\n" +
    "*\n" +
    " *\n"; 
    assertEquals("From: Sin line: 82", null, so.ero(tulos)); 
    so.palauta(); 
  } // Generated by ComTest END
}