package demo.d11.test;
// Generated by ComTest BEGIN
import java.io.IOException;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d11.ValuutatTiedostosta.*;
import demo.d11.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.25 22:10:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ValuutatTiedostostaTest {



  // Generated by ComTest BEGIN
  /** testToString55 */
  @Test
  public void testToString55() {    // ValuutatTiedostosta: 55
    Valuutta euro = new Valuutta("eur", 1.0); 
    assertEquals("From: ValuutatTiedostosta line: 57", "eur 1.00", euro.toString());
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse70 */
  @Test
  public void testParse70() {    // ValuutatTiedostosta: 70
    Valuutta euro = new Valuutta(); 
    euro.parse(" eur  |  1 "); 
    assertEquals("From: ValuutatTiedostosta line: 73", "eur 1.00", euro.toString()); 
    Valuutta dollari = new Valuutta(); 
    dollari.parse(" usd  |  5.7 "); 
    assertEquals("From: ValuutatTiedostosta line: 77", "usd 5.70", dollari.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueValuutat93 
   * @throws IOException when error
   */
  @Test
  public void testLueValuutat93() throws IOException {    // ValuutatTiedostosta: 93
    VertaaTiedosto.kirjoitaTiedosto("testivaluutat.txt",
    "eur|1\n"+
    "usd|0.85\n"+
    "gbp|1.17\n"); 
    var valuutat = lueValuutat("testivaluutat.txt"); 
    assertEquals("From: ValuutatTiedostosta line: 103", "eur 1.00", valuutat.get(0).toString()); 
    assertEquals("From: ValuutatTiedostosta line: 104", "usd 0.85", valuutat.get(1).toString()); 
    assertEquals("From: ValuutatTiedostosta line: 105", "gbp 1.17", valuutat.get(2).toString()); 
    try {
    assertEquals("From: ValuutatTiedostosta line: 106", "eur 1.17", valuutat.get(3).toString()); 
    fail("ValuutatTiedostosta: 106 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    VertaaTiedosto.tuhoaTiedosto("testivaluutat.txt"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVaihdaValuutta160 */
  @Test
  public void testVaihdaValuutta160() {    // ValuutatTiedostosta: 160
    Valuutta euro    = new Valuutta("eur", 1.00); 
    Valuutta dollari = new Valuutta("usd", 0.85); 
    Valuutta punta   = new Valuutta("gbp", 1.17); 
    assertEquals("From: ValuutatTiedostosta line: 165", 1.0, vaihdaValuutta(euro, euro, 1), 0.000001); 
    assertEquals("From: ValuutatTiedostosta line: 166", 1.176470, vaihdaValuutta(euro, dollari, 1), 0.000001); 
    assertEquals("From: ValuutatTiedostosta line: 167", 0.85, vaihdaValuutta(dollari, euro, 1), 0.000001); 
    assertEquals("From: ValuutatTiedostosta line: 168", 0.7264957, vaihdaValuutta(dollari, punta, 1), 0.000001); 
    assertEquals("From: ValuutatTiedostosta line: 169", 1.376470588, vaihdaValuutta(punta, dollari, 1), 0.000001); 
  } // Generated by ComTest END
}