package demo.d12.test;
// Generated by ComTest BEGIN
import demo.d12.Komentorivi.Ynnaa;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import java.io.IOException;
import fi.jyu.mit.ohj2.Suuntaaja;
import demo.d12.Komentorivi.Palindromiko;
import demo.d12.Komentorivi.Komennot;
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d12.Komentorivi.*;
import demo.d12.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.06 11:30:19 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KomentoriviTest {



  // Generated by ComTest BEGIN
  /** testSuorita43 */
  @Test
  public void testSuorita43() {    // Komentorivi: 43
    Ynnaa ynnaa = new Ynnaa(); 
    assertEquals("From: Komentorivi line: 46", "6", ynnaa.suorita("1 2 3")); 
    assertEquals("From: Komentorivi line: 47", "0", ynnaa.suorita("")); 
    assertEquals("From: Komentorivi line: 48", "0", ynnaa.suorita("s")); 
    assertEquals("From: Komentorivi line: 49", "105", ynnaa.suorita("-5 10 100")); 
    assertEquals("From: Komentorivi line: 50", "-895", ynnaa.suorita("-5 10 100 -1000")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testSuorita88 
   * @throws IOException when error
   */
  @Test
  public void testSuorita88() throws IOException {    // Komentorivi: 88
    VertaaTiedosto.kirjoitaTiedosto("lue.txt",
    "[SISÄLLYS] - aina etsitään sisällystä tällä aihe- (topic) nimellä.\n" +
    " Ohjelma osaa tällä hetkellä\n\n" +
    "ynnää - kokonaisluvut\n" +
    "isoksi - jono\n" +
    "palindromiko - jono\n\n" +
    "[YNNÄÄ]\n" +
    "Ynnä\n" +
    "[ISOKSI]\n" +
    "isoksi\n" +
    "[PALINDROMIKO]\n" +
    "palindromi"); 
    Apua apua = new Apua("lue.txt"); 
    assertEquals("From: Komentorivi line: 108", "Ynnä\n", apua.suorita("ynnää")); 
    assertEquals("From: Komentorivi line: 109", "isoksi\n", apua.suorita("Isoksi")); 
    assertEquals("From: Komentorivi line: 110", "palindromi\n", apua.suorita("PALINDROMIKO")); 
    VertaaTiedosto.tuhoaTiedosto("lue.txt"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSuorita143 */
  @Test
  public void testSuorita143() {    // Komentorivi: 143
    Palindromiko pal = new Palindromiko(); 
    assertEquals("From: Komentorivi line: 145", "Sana \"abba\" on palindromi", pal.suorita("abba")); 
    assertEquals("From: Komentorivi line: 146", "Sana \"abbas\" ei ole palindromi", pal.suorita("abbas")); 
    assertEquals("From: Komentorivi line: 147", "Sana \"Saippuakauppias\" on palindromi", pal.suorita("Saippuakauppias")); 
    assertEquals("From: Komentorivi line: 148", "Sana \"\" on palindromi", pal.suorita("")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPalindromi163 */
  @Test
  public void testPalindromi163() {    // Komentorivi: 163
    String sana = "abba"; 
    assertEquals("From: Komentorivi line: 166", true, Palindromiko.palindromi(sana)); 
    sana = "apua"; 
    assertEquals("From: Komentorivi line: 168", false, Palindromiko.palindromi(sana)); 
    sana = "saippuakauppias"; 
    assertEquals("From: Komentorivi line: 170", true, Palindromiko.palindromi(sana)); 
    sana = "Saippuakauppias"; 
    assertEquals("From: Komentorivi line: 172", true, Palindromiko.palindromi(sana)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSuorita197 */
  @Test
  public void testSuorita197() {    // Komentorivi: 197
    Isoksi iso = new Isoksi(); 
    assertEquals("From: Komentorivi line: 199", "", iso.suorita("")); 
    assertEquals("From: Komentorivi line: 200", "ABC", iso.suorita("abc")); 
    assertEquals("From: Komentorivi line: 201", "ABC 3216", iso.suorita("abc 3216")); 
    assertEquals("From: Komentorivi line: 202", "KISSA", iso.suorita("Kissa")); 
    assertEquals("From: Komentorivi line: 203", "ERT-097", iso.suorita("ERt-097")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTulkitse266 */
  @Test
  public void testTulkitse266() {    // Komentorivi: 266
    Komennot komennot = new Komennot(); 
    komennot.add(new Komento("ynnää", new Ynnaa())); 
    String s = "ynnää 2 3 4"; 
    assertEquals("From: Komentorivi line: 271", "9", komennot.tulkitse(s)); 
    s = "ynnaa 2 3 4"; 
    assertEquals("From: Komentorivi line: 273", "komentoa ei tunneta", komennot.tulkitse(s)); 
    s = "ynnää 2 3 4 s"; 
    assertEquals("From: Komentorivi line: 275", "9", komennot.tulkitse(s)); 
    s = "ynnää"; 
    assertEquals("From: Komentorivi line: 277", "0", komennot.tulkitse(s)); 
    s = "ynnää 2"; 
    assertEquals("From: Komentorivi line: 279", "2", komennot.tulkitse(s)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAdd300 */
  @Test
  public void testAdd300() {    // Komentorivi: 300
    Komennot testi = new Komennot(); 
    assertEquals("From: Komentorivi line: 302", 0, testi.size()); 
    testi.add(new Komento("ynnää", new Ynnaa())); 
    assertEquals("From: Komentorivi line: 304", 1, testi.size()); 
    testi.add(new Komento("+", new Ynnaa())); 
    assertEquals("From: Komentorivi line: 306", 2, testi.size()); 
  } // Generated by ComTest END
}