package demo.d12.test;
// Generated by ComTest BEGIN
import demo.d12.NimenKysely.Nimet;
import fi.jyu.mit.ohj2.Suuntaaja;
import demo.d12.NimenKysely.Nimi;
import static org.junit.Assert.*;
import org.junit.*;
import demo.d12.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.07 13:20:29 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class NimenKyselyTest {



  // Generated by ComTest BEGIN
  /** testAdd40 */
  @Test
  public void testAdd40() {    // NimenKysely: 40
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    Nimet nimet = new Nimet(); 
    assertEquals("From: NimenKysely line: 45", 0, nimet.size()); 
    nimet.add("aku ankka"); 
    assertEquals("From: NimenKysely line: 47", 1, nimet.size()); 
    nimet.add("iines ankka"); 
    assertEquals("From: NimenKysely line: 49", 2, nimet.size()); 
    nimet.add("iines "); 
    assertEquals("From: NimenKysely line: 51", 2, nimet.size()); 
    nimet.add("iines"); 
    assertEquals("From: NimenKysely line: 53", 2, nimet.size()); 
    so.palauta(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTulosta78 */
  @Test
  public void testTulosta78() {    // NimenKysely: 78
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    String tulos =
    "Lisätyt nimet olivat:\n" +
    "Aku Ankka\n"+
    "Iines Ankka\n"+
    "Pelle Peloton\n"+
    "Sepe Susi\n"+
    "Pupu Tupuna\n"+
    "Väiski Vemmelsääri\n"; 
    Nimet nimet = new Nimet(); 
    nimet.add("Sepe Susi"); 
    nimet.add("Iines Ankka"); 
    nimet.add("Aku Ankka"); 
    nimet.add("Pelle Peloton"); 
    nimet.add("Väiski Vemmelsääri"); 
    nimet.add("Pupu Tupuna"); 
    nimet.tulosta(); 
    assertEquals("From: NimenKysely line: 101", null, so.ero(tulos)); 
    so.palauta(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse154 */
  @Test
  public void testParse154() {    // NimenKysely: 154
    Nimi uusi = new Nimi(); 
    String virhe = uusi.parse("aku ankka"); 
    assertEquals("From: NimenKysely line: 158", "aku ankka", uusi.toString()); 
    assertEquals("From: NimenKysely line: 159", null, virhe); 
    virhe = uusi.parse("aku"); 
    assertEquals("From: NimenKysely line: 161", "aku ankka", uusi.toString()); 
    assertEquals("From: NimenKysely line: 162", "Syötä nimi muodossa \"Etunimi Sukunimi\"", virhe); 
    virhe = uusi.parse("aku "); 
    assertEquals("From: NimenKysely line: 164", "aku ankka", uusi.toString()); 
    assertEquals("From: NimenKysely line: 165", "Syötä nimi muodossa \"Etunimi Sukunimi\"", virhe); 
    virhe = uusi.parse("Sepe Susi"); 
    assertEquals("From: NimenKysely line: 167", "Sepe Susi", uusi.toString()); 
    assertEquals("From: NimenKysely line: 168", null, virhe); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString200 */
  @Test
  public void testToString200() {    // NimenKysely: 200
    Nimi tupu = new Nimi("Tupu", "Ankka"); 
    assertEquals("From: NimenKysely line: 202", "Tupu Ankka", tupu.toString()); 
    Nimi hupu = new Nimi("Hupu", "Ankka"); 
    assertEquals("From: NimenKysely line: 204", "Hupu Ankka", hupu.toString()); 
  } // Generated by ComTest END
}