package demo.d4.test.test;
// Generated by ComTest BEGIN
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d4.test.TaulukonMuuttaminen2.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.01 15:14:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TaulukonMuuttaminen2Test {


  // Generated by ComTest BEGIN
  /** testKasitteleTaulukko29 */
  @Test
  public void testKasitteleTaulukko29() {    // TaulukonMuuttaminen2: 29
    int[] t; 
    t = new int[]{5, 4, 6, 2, 9, 1}; KasitteleTaulukko(t); assertEquals("From: TaulukonMuuttaminen2 line: 35", "[9, 0, 8, 0, 10, 0]", Arrays.toString(t));  
    t = new int[]{12, 3, 5, -5, 7, 10}; KasitteleTaulukko(t); assertEquals("From: TaulukonMuuttaminen2 line: 36", "[15, 0, 0, 0, 17, 0]", Arrays.toString(t));  
  } // Generated by ComTest END
}