package demo.d4.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d4.Demo.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.04 21:10:55 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class DemoTest {



  // Generated by ComTest BEGIN
  /** testDemohyvitys32 */
  @Test
  public void testDemohyvitys32() {    // Demo: 32
    assertEquals("From: Demo line: 33", 0, demohyvitys(-10, 100)); 
    assertEquals("From: Demo line: 34", 0, demohyvitys(0, 100)); 
    assertEquals("From: Demo line: 35", 0, demohyvitys(100, 0)); 
    assertEquals("From: Demo line: 36", 0, demohyvitys(100, -10)); 
    assertEquals("From: Demo line: 37", 1, demohyvitys(40, 100)); 
    assertEquals("From: Demo line: 38", 1, demohyvitys(49, 100)); 
    assertEquals("From: Demo line: 39", 2, demohyvitys(50, 100)); 
    assertEquals("From: Demo line: 40", 2, demohyvitys(59, 100)); 
    assertEquals("From: Demo line: 41", 3, demohyvitys(60, 100)); 
    assertEquals("From: Demo line: 42", 3, demohyvitys(69, 100)); 
    assertEquals("From: Demo line: 43", 4, demohyvitys(70, 100)); 
    assertEquals("From: Demo line: 44", 4, demohyvitys(79, 100)); 
    assertEquals("From: Demo line: 45", 5, demohyvitys(80, 100)); 
    assertEquals("From: Demo line: 46", 5, demohyvitys(89, 100)); 
    assertEquals("From: Demo line: 47", 6, demohyvitys(90, 100)); 
    assertEquals("From: Demo line: 48", 6, demohyvitys(100, 100)); 
    assertEquals("From: Demo line: 49", 6, demohyvitys(105, 100)); 
  } // Generated by ComTest END
}