package demo.d4.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d4.Tarkkuus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.04 21:10:37 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TarkkuusTest {



  // Generated by ComTest BEGIN
  /** testEtumerkki26 */
  @Test
  public void testEtumerkki26() {    // Tarkkuus: 26
    assertEquals("From: Tarkkuus line: 27", 0, etumerkki(0,0), 0.000001); 
    assertEquals("From: Tarkkuus line: 28", 1, etumerkki(1,0), 0.000001); 
    assertEquals("From: Tarkkuus line: 29", -1, etumerkki(-1,0), 0.000001); 
    assertEquals("From: Tarkkuus line: 30", 0, etumerkki(0.2, 0.5), 0.000001); 
    assertEquals("From: Tarkkuus line: 31", 0, etumerkki(-0.2, 0.5), 0.000001); 
    assertEquals("From: Tarkkuus line: 32", 0, etumerkki(0.0, 0.5), 0.000001); 
    assertEquals("From: Tarkkuus line: 33", 0, etumerkki(-0.5, 0.5), 0.000001); 
    assertEquals("From: Tarkkuus line: 34", 0, etumerkki(0.5, 0.5), 0.000001); 
    assertEquals("From: Tarkkuus line: 35", 1, etumerkki(0.51, 0.5), 0.000001); 
    assertEquals("From: Tarkkuus line: 36", -1, etumerkki(-0.51, 0.5), 0.000001); 
  } // Generated by ComTest END
}