package demo.d9.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import demo.d9.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.12 10:36:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class EhdokasTest {



  // Generated by ComTest BEGIN
  /** testToString30 */
  @Test
  public void testToString30() {    // Ehdokas: 30
    Ehdokas ehd = new Ehdokas(1500.0, 15); 
    assertEquals("From: Ehdokas line: 32", "Rahaa 1500.00, ääniä 15", ehd.toString()); 
    Ehdokas ehd3 = new Ehdokas(0, 0); 
    assertEquals("From: Ehdokas line: 34", "Rahaa 0.00, ääniä 0", ehd3.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testOsta49 */
  @Test
  public void testOsta49() {    // Ehdokas: 49
    Ehdokas ehd1 = new Ehdokas(1000, 300); 
    assertEquals("From: Ehdokas line: 51", "Rahaa 1000.00, ääniä 300", ehd1.toString()); 
    boolean onnistui = ehd1.osta(10, 10); 
    assertEquals("From: Ehdokas line: 53", true, onnistui); 
    assertEquals("From: Ehdokas line: 54", "Rahaa 900.00, ääniä 310", ehd1.toString()); 
    onnistui = ehd1.osta(90, 10); 
    assertEquals("From: Ehdokas line: 56", "Rahaa 0.00, ääniä 400", ehd1.toString()); 
    assertEquals("From: Ehdokas line: 57", true, onnistui); 
    onnistui = ehd1.osta(1, 1); 
    assertEquals("From: Ehdokas line: 59", "Rahaa 0.00, ääniä 400", ehd1.toString()); 
    assertEquals("From: Ehdokas line: 60", false, onnistui); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompareTo79 */
  @Test
  public void testCompareTo79() {    // Ehdokas: 79
    Ehdokas ehd1 = new Ehdokas(1000, 300); 
    Ehdokas ehd2 = new Ehdokas(1000, 300); 
    assertEquals("From: Ehdokas line: 82", 0, ehd1.compareTo(ehd2)); 
    ehd1.osta(1, 100.0); 
    assertEquals("From: Ehdokas line: 84", 1, ehd1.compareTo(ehd2)); 
    ehd2.osta(2, 100.0); 
    assertEquals("From: Ehdokas line: 86", -1, ehd1.compareTo(ehd2)); 
  } // Generated by ComTest END
}