package demo.d9.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import demo.d9.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.12 15:29:49 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class IntTest {



  // Generated by ComTest BEGIN
  /** testSet35 */
  @Test
  public void testSet35() {    // Int: 35
    Int luku = new Int(5); 
    assertEquals("From: Int line: 37", 5, luku.intValue()); 
    luku.set(6); 
    assertEquals("From: Int line: 39", 6, luku.intValue()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIntValue51 */
  @Test
  public void testIntValue51() {    // Int: 51
    Int luku = new Int(5); 
    assertEquals("From: Int line: 53", 5, luku.intValue()); 
    Int luku2 = new Int(-5); 
    assertEquals("From: Int line: 55", -5, luku2.intValue()); 
    Int luku3 = new Int(); 
    assertEquals("From: Int line: 57", 0, luku3.intValue()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString68 */
  @Test
  public void testToString68() {    // Int: 68
    Int luku = new Int(5); 
    assertEquals("From: Int line: 70", "5", luku.toString()); 
    Int luku3 = new Int(); 
    assertEquals("From: Int line: 72", "0", luku3.toString()); 
  } // Generated by ComTest END
}