package demo.d9.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d9.Pnouseva.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.10 12:08:49 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PnousevaTest {



  // Generated by ComTest BEGIN
  /** testPisinNouseva32 */
  @Test
  public void testPisinNouseva32() {    // Pnouseva: 32
    assertEquals("From: Pnouseva line: 33", 3, pisinNouseva("abc")); 
    assertEquals("From: Pnouseva line: 34", 2, pisinNouseva("cab")); 
    assertEquals("From: Pnouseva line: 35", 1, pisinNouseva("cba")); 
    assertEquals("From: Pnouseva line: 36", 4, pisinNouseva("cbaaaa")); 
    assertEquals("From: Pnouseva line: 37", 4, pisinNouseva("abcababcd")); 
    assertEquals("From: Pnouseva line: 38", 0, pisinNouseva("")); 
    assertEquals("From: Pnouseva line: 39", 5, pisinNouseva("ijkabcdeab")); 
  } // Generated by ComTest END
}