package demo.d9.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d9.PoistaTaulukosta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.12 15:24:03 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PoistaTaulukostaTest {



  // Generated by ComTest BEGIN
  /** testPoista17 */
  @Test
  public void testPoista17() {    // PoistaTaulukosta: 17
    int t[] = { 4, 7, 6, 3, 6, 2 } ; 
    int lkm = 6; 
    assertEquals("From: PoistaTaulukosta line: 20", "4 7 6 3 6 2", merkkijonoksi(t, lkm)); 
    lkm = poista(t, lkm, 6); 
    assertEquals("From: PoistaTaulukosta line: 22", 4, lkm);
    assertEquals("From: PoistaTaulukosta line: 23", "4 7 3 2", merkkijonoksi(t, lkm)); 
    int t2[] = { 6, 4, 7, 6, 3, 6, 2 } ; 
    int lkm2 = 7; 
    assertEquals("From: PoistaTaulukosta line: 27", "6 4 7 6 3 6 2", merkkijonoksi(t2, lkm2)); 
    lkm2 = poista(t2, lkm2, 6); 
    assertEquals("From: PoistaTaulukosta line: 29", 4, lkm2);
    assertEquals("From: PoistaTaulukosta line: 30", "4 7 3 2", merkkijonoksi(t2, lkm2)); 
    int t3[] = { 6, 4, 7, 6, 3, 6, 2, 6 } ; 
    int lkm3 = 8; 
    assertEquals("From: PoistaTaulukosta line: 34", "6 4 7 6 3 6 2 6", merkkijonoksi(t3, lkm3)); 
    lkm3 = poista(t3, lkm3, 6); 
    assertEquals("From: PoistaTaulukosta line: 36", 4, lkm3);
    assertEquals("From: PoistaTaulukosta line: 37", "4 7 3 2", merkkijonoksi(t3, lkm3)); 
    int t4[]={ 4,7,9,3,9,2} ; 
    int lkm4 = 6; 
    assertEquals("From: PoistaTaulukosta line: 41", 4, lkm4 = poista(t4, lkm4, 9)); 
    assertEquals("From: PoistaTaulukosta line: 42", "4 7 3 2", merkkijonoksi(t4, lkm4)); 
    assertEquals("From: PoistaTaulukosta line: 43", 3, lkm4 = poista(t4, lkm4, 2)); 
    assertEquals("From: PoistaTaulukosta line: 44", "4 7 3", merkkijonoksi(t4, lkm4)); 
    assertEquals("From: PoistaTaulukosta line: 45", 2, lkm4 = poista(t4, lkm4,4)); 
    assertEquals("From: PoistaTaulukosta line: 46", "7 3", merkkijonoksi(t4, lkm4)); 
  } // Generated by ComTest END
}