package demo.d9.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d9.PoistaTaulukosta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.12 11:53:26 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PoistaTaulukostaTest {



  // Generated by ComTest BEGIN
  /** testPoista22 */
  @Test
  public void testPoista22() {    // PoistaTaulukosta: 22
    int t[] = { 4, 7, 6, 3, 6, 2 } ; 
    int lkm = 6; 
    assertEquals("From: PoistaTaulukosta line: 25", "4 7 6 3 6 2", merkkijonoksi(t, lkm)); 
    lkm = poista(t, lkm, 6); 
    assertEquals("From: PoistaTaulukosta line: 27", 4, lkm);
    assertEquals("From: PoistaTaulukosta line: 28", "4 7 3 2", merkkijonoksi(t, lkm)); 
    int t2[] = { 6, 4, 7, 6, 3, 6, 2 } ; 
    int lkm2 = 7; 
    assertEquals("From: PoistaTaulukosta line: 32", "6 4 7 6 3 6 2", merkkijonoksi(t2, lkm2)); 
    lkm2 = poista(t2, lkm2, 6); 
    assertEquals("From: PoistaTaulukosta line: 34", 4, lkm2);
    assertEquals("From: PoistaTaulukosta line: 35", "4 7 3 2", merkkijonoksi(t2, lkm2)); 
    int t3[] = { 6, 4, 7, 6, 3, 6, 2, 6 } ; 
    int lkm3 = 8; 
    assertEquals("From: PoistaTaulukosta line: 39", "6 4 7 6 3 6 2 6", merkkijonoksi(t3, lkm3)); 
    lkm3 = poista(t3, lkm3, 6); 
    assertEquals("From: PoistaTaulukosta line: 41", 4, lkm3);
    assertEquals("From: PoistaTaulukosta line: 42", "4 7 3 2", merkkijonoksi(t3, lkm3)); 
    int t4[]={ 4,7,9,3,9,2} ; 
    int lkm4 = 6; 
    assertEquals("From: PoistaTaulukosta line: 46", 4, lkm4 = poista(t4, lkm4, 9)); 
    assertEquals("From: PoistaTaulukosta line: 47", "4 7 3 2", merkkijonoksi(t4, lkm4)); 
    assertEquals("From: PoistaTaulukosta line: 48", 3, lkm4 = poista(t4, lkm4, 2)); 
    assertEquals("From: PoistaTaulukosta line: 49", "4 7 3", merkkijonoksi(t4, lkm4)); 
    assertEquals("From: PoistaTaulukosta line: 50", 2, lkm4 = poista(t4, lkm4,4)); 
    assertEquals("From: PoistaTaulukosta line: 51", "7 3", merkkijonoksi(t4, lkm4)); 
  } // Generated by ComTest END
}