package demo.d9.test;
// Generated by ComTest BEGIN
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d9.Vaihtaminen.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.10 10:13:57 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class VaihtaminenTest {



  // Generated by ComTest BEGIN
  /** testKaanna70 */
  @Test
  public void testKaanna70() {    // Vaihtaminen: 70
    int[] t = { 2, 32, 76, 62, 31, 86} ; 
    kaanna(t); 
    assertEquals("From: Vaihtaminen line: 74", "[86, 31, 62, 76, 32, 2]", Arrays.toString(t)); 
    int[] t2 = { 2, 32, 76, 62, 31, 86, 99} ; 
    kaanna(t2); 
    assertEquals("From: Vaihtaminen line: 77", "[99, 86, 31, 62, 76, 32, 2]", Arrays.toString(t2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVaihdaJokaToinen103 */
  @Test
  public void testVaihdaJokaToinen103() {    // Vaihtaminen: 103
    int[] t = { 2, 32, 76, 62, 31, 86} ; 
    vaihdaJokaToinen(t); 
    assertEquals("From: Vaihtaminen line: 107", "[32, 2, 62, 76, 86, 31]", Arrays.toString(t)); 
    int[] t2 = { 2, 32, 76, 62, 31, 86, 99} ; 
    vaihdaJokaToinen(t2); 
    assertEquals("From: Vaihtaminen line: 110", "[32, 2, 62, 76, 86, 31, 99]", Arrays.toString(t2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSummaParillisissaPaikoissa128 */
  @Test
  public void testSummaParillisissaPaikoissa128() {    // Vaihtaminen: 128
    int[] t = { 1,2,3,4,5,6} ; 
    assertEquals("From: Vaihtaminen line: 130", 9, summaParillisissaPaikoissa(t)); 
    assertEquals("From: Vaihtaminen line: 131", 3, summaParillisissaPaikoissa(new int[]{1,1,1,1,1,1})); 
    assertEquals("From: Vaihtaminen line: 132", 0, summaParillisissaPaikoissa(new int[]{})); 
    assertEquals("From: Vaihtaminen line: 133", 1, summaParillisissaPaikoissa(new int[]{1})); 
    assertEquals("From: Vaihtaminen line: 134", 1, summaParillisissaPaikoissa(new int[]{1,2})); 
    assertEquals("From: Vaihtaminen line: 135", 4, summaParillisissaPaikoissa(new int[]{1,2,3})); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSumma154 */
  @Test
  public void testSumma154() {    // Vaihtaminen: 154
    int[] t = { 1,2,3,4,5,6} ; 
    assertEquals("From: Vaihtaminen line: 156", 21, summa(t)); 
    assertEquals("From: Vaihtaminen line: 157", 6, summa(new int[]{1,1,1,1,1,1})); 
    assertEquals("From: Vaihtaminen line: 158", 0, summa(new int[]{})); 
    assertEquals("From: Vaihtaminen line: 159", 1, summa(new int[]{1})); 
    assertEquals("From: Vaihtaminen line: 160", 3, summa(new int[]{1,2})); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSummaPerattaistenErotuksista178 */
  @Test
  public void testSummaPerattaistenErotuksista178() {    // Vaihtaminen: 178
    int[] t = { 1,2,3,4,5,6} ; 
    assertEquals("From: Vaihtaminen line: 180", -3, summaPerattaistenErotuksista(t)); 
    assertEquals("From: Vaihtaminen line: 181", 0, summaPerattaistenErotuksista(new int[]{1,1,1,1,1,1})); 
    assertEquals("From: Vaihtaminen line: 182", 0, summaPerattaistenErotuksista(new int[]{1})); 
    assertEquals("From: Vaihtaminen line: 183", -1, summaPerattaistenErotuksista(new int[]{1,2})); 
    assertEquals("From: Vaihtaminen line: 184", -1, summaPerattaistenErotuksista(new int[]{1,2,3})); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSummaVastaavienErotuksista201 */
  @Test
  public void testSummaVastaavienErotuksista201() {    // Vaihtaminen: 201
    int[] t = { 1,2,3,4,5,6} ; 
    assertEquals("From: Vaihtaminen line: 203", -9, summaVastaavienErotuksista(t)); 
    assertEquals("From: Vaihtaminen line: 204", 0, summaVastaavienErotuksista(new int[]{1,1,1,1,1,1})); 
    assertEquals("From: Vaihtaminen line: 205", 0, summaVastaavienErotuksista(new int[]{1})); 
    assertEquals("From: Vaihtaminen line: 206", -1, summaVastaavienErotuksista(new int[]{1,2})); 
    assertEquals("From: Vaihtaminen line: 207", -2, summaVastaavienErotuksista(new int[]{1,2,3})); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaaArvoihin224 */
  @Test
  public void testLisaaArvoihin224() {    // Vaihtaminen: 224
    int[] t = { 1,2,3,4,5,6} ; 
    lisaaArvoihin(t,5); 
    assertEquals("From: Vaihtaminen line: 228", "[6, 7, 8, 9, 10, 11]", Arrays.toString(t)); 
    assertEquals("From: Vaihtaminen line: 229", "[]", Arrays.toString(lisaaArvoihin(new int[]{},5))); 
    assertEquals("From: Vaihtaminen line: 230", "[6]", Arrays.toString(lisaaArvoihin(new int[]{1},5))); 
    assertEquals("From: Vaihtaminen line: 231", "[4, 5]", Arrays.toString(lisaaArvoihin(new int[]{1,2},3))); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLaskePerakkaiset251 */
  @Test
  public void testLaskePerakkaiset251() {    // Vaihtaminen: 251
    int[] t = { 1,2,3,4,5,6} ; 
    laskePerakkaiset(t); 
    assertEquals("From: Vaihtaminen line: 255", "[3, 0, 7, 0, 11, 0]", Arrays.toString(t)); 
    assertEquals("From: Vaihtaminen line: 256", "[]", Arrays.toString(laskePerakkaiset(new int[]{}))); 
    assertEquals("From: Vaihtaminen line: 257", "[1]", Arrays.toString(laskePerakkaiset(new int[]{1}))); 
    assertEquals("From: Vaihtaminen line: 258", "[3, 0]", Arrays.toString(laskePerakkaiset(new int[]{1,2}))); 
    assertEquals("From: Vaihtaminen line: 259", "[3, 0, 3]", Arrays.toString(laskePerakkaiset(new int[]{1,2,3}))); 
  } // Generated by ComTest END
}