package demo.d6.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d6.Pvm.*;
import demo.d6.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.16 13:31:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PvmTest {



  // Generated by ComTest BEGIN
  /** testPvm24 */
  @Test
  public void testPvm24() {    // Pvm: 24
    Pvm pv1 = new Pvm (15, 3, 2015); 
    assertEquals("From: Pvm line: 26", "15.3.2015", pv1.toString()); 
    Pvm pv2 = new Pvm (45, 3, 2015); 
    assertEquals("From: Pvm line: 29", "0.0.0", pv2.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKarkausvuosi83 */
  @Test
  public void testKarkausvuosi83() {    // Pvm: 83
    assertEquals("From: Pvm line: 84", 0, karkausvuosi(1900));
    assertEquals("From: Pvm line: 85", 0, karkausvuosi(1900));
    assertEquals("From: Pvm line: 86", 0, karkausvuosi(1901));
    assertEquals("From: Pvm line: 87", 1, karkausvuosi(1996));
    assertEquals("From: Pvm line: 88", 1, karkausvuosi(2000));
    assertEquals("From: Pvm line: 89", 0, karkausvuosi(2001));
    assertEquals("From: Pvm line: 90", 1, karkausvuosi(2004));
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAlusta125 */
  @Test
  public void testAlusta125() {    // Pvm: 125
    Pvm pvm = new Pvm(20,2,2012); 
    pvm.alusta(1,3,0); assertEquals("From: Pvm line: 127", "1.3.2012", pvm.toString()); 
    pvm.alusta(2,13,2012); assertEquals("From: Pvm line: 128", "1.3.2012", pvm.toString()); 
    pvm.alusta(28,2,2012); assertEquals("From: Pvm line: 129", "28.2.2012", pvm.toString()); 
    pvm.alusta(29,2,2011); assertEquals("From: Pvm line: 130", "28.2.2012", pvm.toString()); 
    pvm.alusta(29,2,2012); assertEquals("From: Pvm line: 131", "29.2.2012", pvm.toString()); 
    pvm.alusta(31,3,2012); assertEquals("From: Pvm line: 132", "31.3.2012", pvm.toString()); 
    pvm.alusta(31,4,2012); assertEquals("From: Pvm line: 133", "31.3.2012", pvm.toString()); 
    pvm.alusta( 0,2,2012); assertEquals("From: Pvm line: 134", "31.3.2012", pvm.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompareTo171 */
  @Test
  public void testCompareTo171() {    // Pvm: 171
    Pvm pv1 = new Pvm(15,6,2013); 
    Pvm pv2 = new Pvm(14,5,2014); 
    Pvm pv3 = new Pvm(15,7,2014); 
    Pvm pv4 = new Pvm(16,7,2014); 
    Pvm pv5 = new Pvm(16,7,2014); 
    Pvm pv6 = new Pvm(16,7,2012); 
    assertEquals("From: Pvm line: 178", -1, Pvm.compareTo(pv1,pv2));  // ero vuodessa
    assertEquals("From: Pvm line: 179", 1, Pvm.compareTo(pv2,pv1)); 
    assertEquals("From: Pvm line: 180", -1, Pvm.compareTo(pv2,pv3));  // ero kuukaudessa
    assertEquals("From: Pvm line: 181", 1, Pvm.compareTo(pv3,pv2)); 
    assertEquals("From: Pvm line: 182", -1, Pvm.compareTo(pv3,pv4));  // ero päivässä
    assertEquals("From: Pvm line: 183", 1, Pvm.compareTo(pv4,pv3)); 
    assertEquals("From: Pvm line: 184", 0, Pvm.compareTo(pv4,pv5));  // kaikki samoja
    assertEquals("From: Pvm line: 185", -1, Pvm.compareTo(pv6,pv2));  // ero kuukaudessa, mutta vuodessa toisinpäin
    assertEquals("From: Pvm line: 186", 1, Pvm.compareTo(pv2,pv6)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompareTo211 */
  @Test
  public void testCompareTo211() {    // Pvm: 211
    Pvm pv1 = new Pvm(15,6,2013); 
    Pvm pv2 = new Pvm(14,5,2014); 
    Pvm pv3 = new Pvm(15,7,2014); 
    Pvm pv4 = new Pvm(16,7,2014); 
    Pvm pv5 = new Pvm(16,7,2014); 
    Pvm pv6 = new Pvm(16,7,2012); 
    assertEquals("From: Pvm line: 218", -1, pv1.compareTo(pv2));  // ero vuodessa
    assertEquals("From: Pvm line: 219", 1, pv2.compareTo(pv1)); 
    assertEquals("From: Pvm line: 220", -1, pv2.compareTo(pv3));  // ero kuukaudessa
    assertEquals("From: Pvm line: 221", 1, pv3.compareTo(pv2)); 
    assertEquals("From: Pvm line: 222", -1, pv3.compareTo(pv4));  // ero päivässä
    assertEquals("From: Pvm line: 223", 1, pv4.compareTo(pv3)); 
    assertEquals("From: Pvm line: 224", 0, pv4.compareTo(pv5));  // kaikki samoja
    assertEquals("From: Pvm line: 225", -1, pv6.compareTo(pv2));  // ero kuukaudessa, mutta vuodessa toisinpäin
    assertEquals("From: Pvm line: 226", 1, pv2.compareTo(pv6)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals248 */
  @Test
  public void testEquals248() {    // Pvm: 248
    Pvm pv1 = new Pvm(15,3,2015); 
    Pvm pv2 = new Pvm(15,3,2015); 
    assertEquals("From: Pvm line: 251", true, pv1.equals(pv2)); 
    pv2.alusta(16,0,0); 
    assertEquals("From: Pvm line: 254", false, pv1.equals(pv2)); 
    pv1.alusta(17,0,0); 
    assertEquals("From: Pvm line: 257", false, pv1.equals(pv2)); 
  } // Generated by ComTest END
}