package demo.d6.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d6.Pvm.*;
import demo.d6.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.14 20:09:57 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PvmTest {



  // Generated by ComTest BEGIN
  /** testPvm25 */
  @Test
  public void testPvm25() {    // Pvm: 25
    Pvm pv1 = new Pvm (15, 3, 2015); 
    assertEquals("From: Pvm line: 27", "15.3.2015", pv1.toString()); 
    Pvm pv2 = new Pvm (45, 3, 2015); 
    assertEquals("From: Pvm line: 30", "0.0.0", pv2.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKarkausvuosi84 */
  @Test
  public void testKarkausvuosi84() {    // Pvm: 84
    assertEquals("From: Pvm line: 85", 0, karkausvuosi(1900));
    assertEquals("From: Pvm line: 86", 0, karkausvuosi(1900));
    assertEquals("From: Pvm line: 87", 0, karkausvuosi(1901));
    assertEquals("From: Pvm line: 88", 1, karkausvuosi(1996));
    assertEquals("From: Pvm line: 89", 1, karkausvuosi(2000));
    assertEquals("From: Pvm line: 90", 0, karkausvuosi(2001));
    assertEquals("From: Pvm line: 91", 1, karkausvuosi(2004));
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAlusta107 */
  @Test
  public void testAlusta107() {    // Pvm: 107
    Pvm pvm = new Pvm(15, 3, 2015); 
    assertEquals("From: Pvm line: 109", "15.3.2015", pvm.toString()); 
    pvm.alusta(16, 4, 2016); 
    assertEquals("From: Pvm line: 112", "16.4.2016", pvm.toString()); 
    pvm.alusta(17, 5, 20150); 
    assertEquals("From: Pvm line: 115", "17.5.20150", pvm.toString()); 
    pvm.alusta(0, 0, 2003); 
    assertEquals("From: Pvm line: 118", "17.5.2003", pvm.toString()); 
    pvm.alusta(29, 2, 2020); 
    assertEquals("From: Pvm line: 121", "29.2.2020", pvm.toString()); 
    pvm.alusta(0, 0, 2021); 
    assertEquals("From: Pvm line: 124", "29.2.2020", pvm.toString()); 
    pvm.alusta(28, 0, 2021); 
    assertEquals("From: Pvm line: 127", "28.2.2021", pvm.toString()); 
    pvm.alusta(31,3,2021); 
    assertEquals("From: Pvm line: 130", "31.3.2021", pvm.toString()); 
    pvm.alusta(0,4,2021); 
    assertEquals("From: Pvm line: 133", "31.3.2021", pvm.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompareTo179 */
  @Test
  public void testCompareTo179() {    // Pvm: 179
    Pvm pv1 = new Pvm(15,3,2015); 
    Pvm pv2 = new Pvm(15,3,2015); 
    assertEquals("From: Pvm line: 182", 0, compareTo(pv1, pv2)); 
    pv2.alusta(16,0,0); 
    assertEquals("From: Pvm line: 185", -1, compareTo(pv1, pv2)); 
    pv1.alusta(17,0,0); 
    assertEquals("From: Pvm line: 188", 1, compareTo(pv1, pv2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompareTo207 */
  @Test
  public void testCompareTo207() {    // Pvm: 207
    Pvm pv1 = new Pvm(15,3,2015); 
    Pvm pv2 = new Pvm(15,3,2015); 
    assertEquals("From: Pvm line: 210", 0, pv1.compareTo(pv2)); 
    pv2.alusta(16,0,0); 
    assertEquals("From: Pvm line: 213", -1, pv1.compareTo(pv2)); 
    pv1.alusta(17,0,0); 
    assertEquals("From: Pvm line: 216", 1, pv1.compareTo(pv2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals233 */
  @Test
  public void testEquals233() {    // Pvm: 233
    Pvm pv1 = new Pvm(15,3,2015); 
    Pvm pv2 = new Pvm(15,3,2015); 
    assertEquals("From: Pvm line: 236", true, pv1.equals(pv2)); 
    pv2.alusta(16,0,0); 
    assertEquals("From: Pvm line: 239", false, pv1.equals(pv2)); 
    pv1.alusta(17,0,0); 
    assertEquals("From: Pvm line: 242", false, pv1.equals(pv2)); 
  } // Generated by ComTest END
}