package demo.d6.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d6.TaulukonKasittely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.14 21:52:41 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TaulukonKasittelyTest {



  // Generated by ComTest BEGIN
  /** testPienimmanPaikka30 */
  @Test
  public void testPienimmanPaikka30() {    // TaulukonKasittely: 30
    int t[] = { 3,2,1,2,3} ; 
    assertEquals("From: TaulukonKasittely line: 32", 2, pienimmanPaikka(t)); 
    int t2[] = { 1,2,3,2,3} ; 
    assertEquals("From: TaulukonKasittely line: 35", 0, pienimmanPaikka(t2)); 
    int t3[] = { 3,2,3,2,1} ; 
    assertEquals("From: TaulukonKasittely line: 38", 4, pienimmanPaikka(t3)); 
    int t5[] = { 3,1,3,2,1} ; 
    assertEquals("From: TaulukonKasittely line: 41", 1, pienimmanPaikka(t5)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPienin63 */
  @Test
  public void testPienin63() {    // TaulukonKasittely: 63
    int t[] = { 3,2,1,2,3} ; 
    assertEquals("From: TaulukonKasittely line: 65", 1, pienin(t)); 
    int t2[] = { -1,2,3,2,3} ; 
    assertEquals("From: TaulukonKasittely line: 68", -1, pienin(t2)); 
    int t3[] = { 3,2,3,2,-100} ; 
    assertEquals("From: TaulukonKasittely line: 71", -100, pienin(t3)); 
    int t5[] = { 3,1,3,2,1} ; 
    assertEquals("From: TaulukonKasittely line: 74", 1, pienin(t5)); 
  } // Generated by ComTest END
}