package demo.d8.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d8.Kirje.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.24 15:46:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjeTest {



  // Generated by ComTest BEGIN
  /** testPostimaksuDoubleTaulukko37 */
  @Test
  public void testPostimaksuDoubleTaulukko37() {    // Kirje: 37
    assertEquals("From: Kirje line: 38", -1, postimaksuDoubleTaulukko(-100), 0.000001); 
    assertEquals("From: Kirje line: 39", 1.00, postimaksuDoubleTaulukko(0), 0.000001); 
    assertEquals("From: Kirje line: 40", 1.00, postimaksuDoubleTaulukko(45), 0.000001); 
    assertEquals("From: Kirje line: 41", 1.00, postimaksuDoubleTaulukko(50), 0.000001); 
    assertEquals("From: Kirje line: 42", 1.40, postimaksuDoubleTaulukko(100), 0.000001); 
    assertEquals("From: Kirje line: 43", 2.00, postimaksuDoubleTaulukko(249), 0.000001); 
    assertEquals("From: Kirje line: 44", 6.00, postimaksuDoubleTaulukko(501), 0.000001); 
    assertEquals("From: Kirje line: 45", 6.00, postimaksuDoubleTaulukko(999), 0.000001); 
    assertEquals("From: Kirje line: 46", 6.00, postimaksuDoubleTaulukko(1000), 0.000001); 
    assertEquals("From: Kirje line: 47", 10.00, postimaksuDoubleTaulukko(1999), 0.000001); 
    assertEquals("From: Kirje line: 48", 10.00, postimaksuDoubleTaulukko(2000), 0.000001); 
    assertEquals("From: Kirje line: 49", -1.00, postimaksuDoubleTaulukko(2001), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPostimaksu66 */
  @Test
  public void testPostimaksu66() {    // Kirje: 66
    assertEquals("From: Kirje line: 67", -1, postimaksu(-100), 0.000001); 
    assertEquals("From: Kirje line: 68", 1.00, postimaksu(0), 0.000001); 
    assertEquals("From: Kirje line: 69", 1.00, postimaksu(45), 0.000001); 
    assertEquals("From: Kirje line: 70", 1.00, postimaksu(50), 0.000001); 
    assertEquals("From: Kirje line: 71", 1.40, postimaksu(100), 0.000001); 
    assertEquals("From: Kirje line: 72", 2.00, postimaksu(249), 0.000001); 
    assertEquals("From: Kirje line: 73", 6.00, postimaksu(501), 0.000001); 
    assertEquals("From: Kirje line: 74", 6.00, postimaksu(999), 0.000001); 
    assertEquals("From: Kirje line: 75", 6.00, postimaksu(1000), 0.000001); 
    assertEquals("From: Kirje line: 76", 10.00, postimaksu(1999), 0.000001); 
    assertEquals("From: Kirje line: 77", 10.00, postimaksu(2000), 0.000001); 
    assertEquals("From: Kirje line: 78", -1.0, postimaksu(2001), 0.000001); 
  } // Generated by ComTest END
}