package demo.d8.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d8.Matriisi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.24 11:40:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MatriisiTest {



  // Generated by ComTest BEGIN
  /** testSumma33 */
  @Test
  public void testSumma33() {    // Matriisi: 33
    double[][] t = new double[][] { { 1,2,3} ,{ 4,5,6} } ; 
    assertEquals("From: Matriisi line: 35", 21, summa(t), 0.000001); 
    double[][] t1 = new double[][] { { 1,2,3} ,{ 4,5,6} ,{ 1,2,3} } ; 
    assertEquals("From: Matriisi line: 37", 27, summa(t1), 0.000001); 
    double[][] t2 = new double[][] { { } ,{ } } ; 
    assertEquals("From: Matriisi line: 39", 0, summa(t2), 0.000001); 
    double[][] t3 = new double[][] { { -1,-2,-3} ,{ 1,2,3} } ; 
    assertEquals("From: Matriisi line: 41", 0, summa(t3), 0.000001); 
    double[][] t4 = new double[][] { { -1} ,{ 3} } ; 
    assertEquals("From: Matriisi line: 43", 2, summa(t4), 0.000001); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSumma62 */
  @Test
  public void testSumma62() {    // Matriisi: 62
    double[] taulukko = new double[] { 1.2, 2, 3, 4, 5} ; 
    assertEquals("From: Matriisi line: 64", 15.2, summa(taulukko), 0.000001); 
    double[] taulukko2 = new double[] { -1.2, -2, -3, -4, -5} ; 
    assertEquals("From: Matriisi line: 66", -15.2, summa(taulukko2), 0.000001); 
    double[] taulukko3 = new double[] { } ; 
    assertEquals("From: Matriisi line: 68", 0, summa(taulukko3), 0.000001); 
  } // Generated by ComTest END
}