package demo.d8.test;
// Generated by ComTest BEGIN
import java.util.Calendar;
import static org.junit.Assert.*;
import org.junit.*;
import demo.d8.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.24 13:56:18 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PvmTest {



  // Generated by ComTest BEGIN
  /** testPvm22 */
  @Test
  public void testPvm22() {    // Pvm: 22
    Pvm testi = new Pvm(1, 2, 1995); 
    assertEquals("From: Pvm line: 24", 1, testi.getPv()); 
    assertEquals("From: Pvm line: 25", 2, testi.getKk()); 
    assertEquals("From: Pvm line: 26", 1995, testi.getVv()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPvm40 */
  @Test
  public void testPvm40() {    // Pvm: 40
    Calendar nyt = Calendar.getInstance(); 
    int vv = nyt.get(Calendar.YEAR); 
    Pvm pvm = new Pvm(2, 3); 
    assertEquals("From: Pvm line: 45", 2, pvm.getPv()); 
    assertEquals("From: Pvm line: 46", 3, pvm.getKk()); 
    assertEquals("From: Pvm line: 47", vv, pvm.getVv()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPvm60 */
  @Test
  public void testPvm60() {    // Pvm: 60
    Calendar nyt = Calendar.getInstance(); 
    int kk = nyt.get(Calendar.MONTH) - Calendar.JANUARY + 1; 
    int vv = nyt.get(Calendar.YEAR); 
    Pvm pvm = new Pvm(2); 
    assertEquals("From: Pvm line: 66", 2, pvm.getPv()); 
    assertEquals("From: Pvm line: 67", kk, pvm.getKk()); 
    assertEquals("From: Pvm line: 68", vv, pvm.getVv()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPvm79 */
  @Test
  public void testPvm79() {    // Pvm: 79
    Calendar nyt = Calendar.getInstance(); 
    int pv = nyt.get(Calendar.DATE); 
    int kk = nyt.get(Calendar.MONTH) - Calendar.JANUARY + 1; 
    int vv = nyt.get(Calendar.YEAR); 
    Pvm pvm = new Pvm(); 
    assertEquals("From: Pvm line: 86", pv, pvm.getPv()); 
    assertEquals("From: Pvm line: 87", kk, pvm.getKk()); 
    assertEquals("From: Pvm line: 88", vv, pvm.getVv()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPvm100 */
  @Test
  public void testPvm100() {    // Pvm: 100
    Calendar nyt = Calendar.getInstance(); 
    int pv = nyt.get(Calendar.DATE); 
    int kk = nyt.get(Calendar.MONTH) - Calendar.JANUARY + 1; 
    int vv = nyt.get(Calendar.YEAR); 
    Pvm pvm; 
    pvm = new Pvm(1, 1); assertEquals("From: Pvm line: 111", "1.1."+vv, pvm.toString());  
    pvm = new Pvm(1); assertEquals("From: Pvm line: 112", 1+"."+kk+"."+vv, pvm.toString());  
    pvm = new Pvm(); assertEquals("From: Pvm line: 113", pv+"."+kk+"."+vv, pvm.toString());  
    pvm = new Pvm(1, 3, 97); assertEquals("From: Pvm line: 114", "1.3.1997", pvm.toString());  
    pvm = new Pvm("1.5"); assertEquals("From: Pvm line: 115", "1.5."+vv, pvm.toString());  
    pvm = new Pvm("1..1990"); assertEquals("From: Pvm line: 116", "1."+kk+".1990", pvm.toString());  
    pvm = new Pvm("..1990"); assertEquals("From: Pvm line: 117", pv+"."+kk+".1990", pvm.toString());  
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPaivays162 */
  @Test
  public void testPaivays162() {    // Pvm: 162
    Calendar nyt = Calendar.getInstance(); 
    int pv = nyt.get(Calendar.DATE); 
    int kk = nyt.get(Calendar.MONTH) - Calendar.JANUARY + 1; 
    int vv = nyt.get(Calendar.YEAR); 
    Pvm pvm = new Pvm(); 
    pvm.paivays(); 
    assertEquals("From: Pvm line: 170", pv, pvm.getPv()); 
    assertEquals("From: Pvm line: 171", kk, pvm.getKk()); 
    assertEquals("From: Pvm line: 172", vv, pvm.getVv()); 
  } // Generated by ComTest END
}