package demo.d8.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d8.Taulukot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.05 12:32:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TaulukotTest {



  // Generated by ComTest BEGIN
  /** testMatriisinSuurin21 */
  @Test
  public void testMatriisinSuurin21() {    // Taulukot: 21
    double mat[][] = { { 1, 2, 3, 4 } , { 5, 6, 7, 8 } } ; 
    assertEquals("From: Taulukot line: 23", 8, matriisinSuurin(mat), 0.000001); 
    double mat2[][] = { { 1, 2, 3, 4 } , { 10, 6, 7, 8 } } ; 
    assertEquals("From: Taulukot line: 25", 10, matriisinSuurin(mat2), 0.000001); 
    double mat3[][] = { { 1, 2, 3, 11 } , { 10, 6, 7, 8 } } ; 
    assertEquals("From: Taulukot line: 27", 11, matriisinSuurin(mat3), 0.000001); 
    double mat4[][] = { { 12, 2, 3, 11 } , { 10, 6, 7, 8 } } ; 
    assertEquals("From: Taulukot line: 29", 12, matriisinSuurin(mat4), 0.000001); 
    double mat5[][] = { { } , { } } ; 
    assertEquals("From: Taulukot line: 31", Double.MIN_VALUE, matriisinSuurin(mat5), 0.000001); 
  } // Generated by ComTest END
}