package demo.d3.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d3.Esiintymat.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.01 10:39:24 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class EsiintymatTest {



  // Generated by ComTest BEGIN
  /** testPoistaEsiintymat27 */
  @Test
  public void testPoistaEsiintymat27() {    // Esiintymat: 27
    poistaEsiintymat("Catcat", "at").equals("Cc"); 
    poistaEsiintymat("Paatti", "at").equals("Pi"); 
    poistaEsiintymat("Puatit", "at").equals("Puit"); 
    poistaEsiintymat("atiu", "at").equals("iu"); 
    poistaEsiintymat("atatiu", "at").equals("iu"); 
    poistaEsiintymat("kissaisis", "is").equals("ksa"); 
  } // Generated by ComTest END
}