package demo.d3.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d3.Etusuku.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.01.27 15:50:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class EtusukuTest {



  // Generated by ComTest BEGIN
  /** testErota23 */
  @Test
  public void testErota23() {    // Etusuku: 23
    StringBuilder jono = new StringBuilder("123 456"); String s; 
    s = erota(jono,' ',false); assertEquals("From: Etusuku line: 25", "456", jono.toString()); assertEquals("From: Etusuku line: 25", "123", s); 
    s = erota(jono,' ',false); assertEquals("From: Etusuku line: 26", "", jono.toString()); assertEquals("From: Etusuku line: 26", "456", s); 
    jono = new StringBuilder("1 2 3"); 
    assertEquals("From: Etusuku line: 28", "1", erota(jono,' ',false)); 
    assertEquals("From: Etusuku line: 29", "2", erota(jono,' ',false)); 
    assertEquals("From: Etusuku line: 30", "3", erota(jono,' ',false)); 
    assertEquals("From: Etusuku line: 31", "", erota(jono,' ',false)); 
    assertEquals("From: Etusuku line: 32", "", erota(jono,' ',false)); 
    jono = new StringBuilder("123 456 789"); 
    assertEquals("From: Etusuku line: 34", "123 456", erota(jono,' ',true));
    assertEquals("From: Etusuku line: 35", "789", erota(jono,' ',true));
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testErota62 */
  @Test
  public void testErota62() {    // Etusuku: 62
    StringBuilder jono = new StringBuilder("1 2 3"); 
    assertEquals("From: Etusuku line: 64", "1", erota(jono,' ')); 
    assertEquals("From: Etusuku line: 65", "2", erota(jono,' ')); 
    assertEquals("From: Etusuku line: 66", "3", erota(jono,' ')); 
    assertEquals("From: Etusuku line: 67", "", erota(jono,' ')); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testErota80 */
  @Test
  public void testErota80() {    // Etusuku: 80
    StringBuilder jono = new StringBuilder("1 2 3"); 
    assertEquals("From: Etusuku line: 82", "1", erota(jono)); 
    assertEquals("From: Etusuku line: 83", "2", erota(jono)); 
    assertEquals("From: Etusuku line: 84", "3", erota(jono)); 
    assertEquals("From: Etusuku line: 85", "", erota(jono)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVaihdaAlkuLoppu101 */
  @Test
  public void testVaihdaAlkuLoppu101() {    // Etusuku: 101
    assertEquals("From: Etusuku line: 102", "Ankka Aku", vaihdaAlkuLoppu("Aku Ankka", ' ', false)); 
    assertEquals("From: Etusuku line: 103", "Palo Jukka Pekka", vaihdaAlkuLoppu("Jukka Pekka Palo", ' ', true)); 
    assertEquals("From: Etusuku line: 104", "Aku", vaihdaAlkuLoppu("Aku", ' ', false)); 
    assertEquals("From: Etusuku line: 105", "", vaihdaAlkuLoppu("", ' ', false)); 
    assertEquals("From: Etusuku line: 106", "tama.toimii", vaihdaAlkuLoppu("toimii.tama", '.', false)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVaihdaEtuSuku124 */
  @Test
  public void testVaihdaEtuSuku124() {    // Etusuku: 124
    assertEquals("From: Etusuku line: 125", "", vaihdaEtuSuku(""));
    assertEquals("From: Etusuku line: 126", "", vaihdaEtuSuku(" "));
    assertEquals("From: Etusuku line: 127", "Pele", vaihdaEtuSuku("Pele"));
    assertEquals("From: Etusuku line: 128", "Ankka Aku", vaihdaEtuSuku("Aku Ankka"));
    assertEquals("From: Etusuku line: 129", "Palo Jukka Pekka", vaihdaEtuSuku("Jukka Pekka Palo"));
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVaihdaSukuEtu143 */
  @Test
  public void testVaihdaSukuEtu143() {    // Etusuku: 143
    assertEquals("From: Etusuku line: 144", "", vaihdaSukuEtu(""));
    assertEquals("From: Etusuku line: 145", "Pele", vaihdaSukuEtu("Pele"));
    assertEquals("From: Etusuku line: 146", "Aku Ankka", vaihdaSukuEtu("Ankka Aku"));
    assertEquals("From: Etusuku line: 147", "Jukka Pekka Palo", vaihdaSukuEtu("Palo Jukka Pekka"));
  } // Generated by ComTest END
}