package demo.d3.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d3.Jarjesta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.01.29 12:45:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JarjestaTest {



  // Generated by ComTest BEGIN
  /** testJarjesta1ja228 */
  @Test
  public void testJarjesta1ja228() {    // Jarjesta: 28
    jarjesta1ja2("").equals(""); 
    jarjesta1ja2("kissa").equals("kissa"); 
    jarjesta1ja2("kissa ").equals("kissa"); 
    jarjesta1ja2(" kissa").equals("kissa"); 
    jarjesta1ja2("aa ab").equals("aa ab"); 
    jarjesta1ja2("ab aa").equals("aa ab"); 
    jarjesta1ja2("ah ihanaa").equals("ah ihanaa"); 
    jarjesta1ja2("ihanaa ah").equals("ah ihanaa"); 
    jarjesta1ja2("ihanaa ah tämä ohjelmointi").equals("ah ihanaa"); 
    jarjesta1ja2("ah ihanaa tämä ohjelmointi").equals("ah ihanaa"); 
  } // Generated by ComTest END
}