package demo.d3.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d3.Jokerimerkki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.01.27 15:38:48 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JokerimerkkiTest {



  // Generated by ComTest BEGIN
  /** testOnkoSamatKysymysmerkilla28 */
  @Test
  public void testOnkoSamatKysymysmerkilla28() {    // Jokerimerkki: 28
    assertEquals("From: Jokerimerkki line: 29", true, onkoSamatKysymysmerkilla("kissa", "kissa")); 
    assertEquals("From: Jokerimerkki line: 30", false, onkoSamatKysymysmerkilla("kissa", "koira")); 
    assertEquals("From: Jokerimerkki line: 31", false, onkoSamatKysymysmerkilla("kissa", "kiss")); 
    assertEquals("From: Jokerimerkki line: 32", false, onkoSamatKysymysmerkilla("kis", "kissa")); 
    assertEquals("From: Jokerimerkki line: 33", true, onkoSamatKysymysmerkilla("kissa", "kiss?")); 
    assertEquals("From: Jokerimerkki line: 34", true, onkoSamatKysymysmerkilla("kissa", "?issa")); 
    assertEquals("From: Jokerimerkki line: 35", true, onkoSamatKysymysmerkilla("kissa", "ki?sa")); 
    assertEquals("From: Jokerimerkki line: 36", true, onkoSamatKysymysmerkilla("", "")); 
    assertEquals("From: Jokerimerkki line: 37", true, onkoSamatKysymysmerkilla("oke", "???")); 
  } // Generated by ComTest END
}