package demo.d10.test;
// Generated by ComTest BEGIN
import java.io.ByteArrayOutputStream;
import demo.d10.Koulu;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.17 22:12:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KouluTest {



  // Generated by ComTest BEGIN
  /** testLisaa69 */
  @Test
  public void testLisaa69() {    // Koulu: 69
    ByteArrayOutputStream bs  = new ByteArrayOutputStream(); 
    String alku =  "%n%nLuokka: 1b oppilaita: %d%n" +
    "==========================================%n"; 
    String loppu = "==========================================%n"; 
    String t = ""; 
    Koulu luokka = new Koulu("1b"); 
    ; 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 86", String.format(alku+(t="")+loppu,0), bs.toString()); bs.reset();  
    luokka.lisaa(new Koulu.Oppilas("Ankka Aku",5.0)); 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 87", String.format(alku+(t+="Ankka Aku              keskiarvo:  5.00%n")+loppu,1), bs.toString()); bs.reset();  
    luokka.lisaa(new Koulu.Oppilas("Ankka Tupu",7.0)); 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 88", String.format(alku+(t+="Ankka Tupu             keskiarvo:  7.00%n")+loppu,2), bs.toString()); bs.reset();  
    luokka.lisaa(new Koulu.Oppilas("Hiiri Mikki",9.0)); 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 89", String.format(alku+(t+="Hiiri Mikki            keskiarvo:  9.00%n")+loppu,3), bs.toString()); bs.reset();  
    luokka.poistaKaikki(); 
    ; 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 100", String.format(alku+(t="")+loppu,0), bs.toString()); bs.reset();  
    luokka.lisaa(new Koulu.Oppilas("Hiiri Mikki",9.0)); 
    luokka.tulosta(bs); 
    assertEquals("From: Koulu line: 101", String.format(alku+(t+="Hiiri Mikki            keskiarvo:  9.00%n")+loppu,1), bs.toString()); bs.reset();  
    Koulu kakkosluokka = new Koulu("2a"); 
    kakkosluokka.lisaa(new Koulu.Oppilas("Seppo Siili",7.5)); 
    assertEquals("From: Koulu line: 106", "Seppo Siili            keskiarvo:  7.50", kakkosluokka.annaEka().toString()); 
    assertEquals("From: Koulu line: 107", 1, kakkosluokka.oppilasMaara()); 
    assertEquals("From: Koulu line: 108", "Seppo Siili            keskiarvo:  7.50", kakkosluokka.annaEka().toString()); 
    assertEquals("From: Koulu line: 109", "Seppo Siili            keskiarvo:  7.50", kakkosluokka.annaVika().toString()); 
    kakkosluokka.lisaa(new Koulu.Oppilas("Keijo Kala",9.5)); 
    assertEquals("From: Koulu line: 111", "Keijo Kala             keskiarvo:  9.50", kakkosluokka.annaEka().annaSeuraava().toString()); 
    assertEquals("From: Koulu line: 112", 2, kakkosluokka.oppilasMaara()); 
    assertEquals("From: Koulu line: 113", "Seppo Siili            keskiarvo:  7.50", kakkosluokka.annaEka().toString()); 
    assertEquals("From: Koulu line: 114", "Keijo Kala             keskiarvo:  9.50", kakkosluokka.annaVika().toString()); 
    kakkosluokka.lisaa(new Koulu.Oppilas("Sulo Siiseli",4.5)); 
    assertEquals("From: Koulu line: 116", "Sulo Siiseli           keskiarvo:  4.50", kakkosluokka.annaEka().annaSeuraava().annaSeuraava().toString()); 
    assertEquals("From: Koulu line: 117", 3, kakkosluokka.oppilasMaara()); 
    assertEquals("From: Koulu line: 118", "Seppo Siili            keskiarvo:  7.50", kakkosluokka.annaEka().toString()); 
    assertEquals("From: Koulu line: 119", "Sulo Siiseli           keskiarvo:  4.50", kakkosluokka.annaVika().toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaKaikki135 */
  @Test
  public void testPoistaKaikki135() {    // Koulu: 135
    Koulu kolmosluokka = new Koulu("3a"); 
    kolmosluokka.lisaa(new Koulu.Oppilas("Seppo Siili",7.5)); 
    kolmosluokka.lisaa(new Koulu.Oppilas("Keijo Kala",9.5)); 
    kolmosluokka.lisaa(new Koulu.Oppilas("Sulo Siiseli",4.5)); 
    assertEquals("From: Koulu line: 140", 3, kolmosluokka.oppilasMaara()); 
    kolmosluokka.poistaKaikki(); 
    assertEquals("From: Koulu line: 142", 0, kolmosluokka.oppilasMaara()); 
    assertEquals("From: Koulu line: 143", null, kolmosluokka.annaEka()); 
    assertEquals("From: Koulu line: 144", null, kolmosluokka.annaVika()); 
  } // Generated by ComTest END
}