package demo.d10.test;
// Generated by ComTest BEGIN
import fi.jyu.mit.ohj2.Suuntaaja;
import java.io.IOException;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d10.TiedNumerointi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.16 13:22:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TiedNumerointiTest {



  // Generated by ComTest BEGIN
  /** 
   * testMain26 
   * @throws IOException when error
   */
  @Test
  public void testMain26() throws IOException {    // TiedNumerointi: 26
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    VertaaTiedosto.kirjoitaTiedosto("lue.txt",
    "123456789012345678901234567890123456789012345678901234567890\n"+
    "Kissa istuu puussa\n"+
    "ja ihmettelee\n"+
    "mualiman menoa\n"); 
    String tulos =
    "/" +"*"+ " 0" +"1" +" *"+"/"  +" 1234567890123456789012345678901234567890\n" +
    "/" +"*"+ " 0" +"2" +" *"+"/"  +" Kissa istuu puussa\n" +
    "/" +"*"+ " 0" +"3" +" *"+"/"  +" ja ihmettelee\n" +
    "/" +"*"+ " 0" +"4" +" *"+"/"  +" mualiman menoa\n"; 
    main(new String[]{"lue.txt"}); 
    assertEquals("From: TiedNumerointi line: 45", null, so.ero(tulos)); 
    so.palauta(); 
    VertaaTiedosto.tuhoaTiedosto("lue.txt"); 
  } // Generated by ComTest END
}