package demo.d10.test;
// Generated by ComTest BEGIN
import java.io.IOException;
import fi.jyu.mit.ohj2.VertaaTiedosto;
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d10.TiedostonNumerointi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.16 13:10:24 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TiedostonNumerointiTest {


  // Generated by ComTest BEGIN
  /** 
   * testMain26 
   * @throws IOException when error
   */
  @Test
  public void testMain26() throws IOException {    // TiedostonNumerointi: 26
    VertaaTiedosto.kirjoitaTiedosto("lue.txt",
    "123456789012345678901234567890123456789012345678901234567890\n"+
    "Kissa istuu puussa\n"+
    "ja ihmettelee\n"+
    "mualiman menoa\n"); 
    String tulos =
    "/" +"*"+ " 0" +"1" +" *"+"/"  +" 1234567890123456789012345678901234567890\n" +
    "/" +"*"+ " 0" +"2" +" *"+"/"  +" Kissa istuu puussa\n" +
    "/" +"*"+ " 0" +"3" +" *"+"/"  +" ja ihmettelee\n" +
    "/" +"*"+ " 0" +"4" +" *"+"/"  +" mualiman menoa\n"; 
    VertaaTiedosto.tuhoaTiedosto("tulos.txt"); 
    main(new String[]{"lue.txt","tulos.txt"}); 
    assertEquals("From: TiedostonNumerointi line: 42", null, VertaaTiedosto.vertaaFileString("tulos.txt",tulos)); 
    VertaaTiedosto.tuhoaTiedosto("tulos.txt"); 
    VertaaTiedosto.tuhoaTiedosto("lue.txt"); 
  } // Generated by ComTest END
}