package demo.d5.test;
// Generated by ComTest BEGIN
import java.io.*;
import static org.junit.Assert.*;
import org.junit.*;
import demo.d5.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.09 15:56:15 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HenkiloTest {



  // Generated by ComTest BEGIN
  /** testGetNimi57 */
  @Test
  public void testGetNimi57() {    // Henkilo: 57
    Henkilo aku = new Henkilo("Aku","Ankka",1934); 
    assertEquals("From: Henkilo line: 59", "Aku Ankka", aku.getNimi()); 
    Henkilo pele = new Henkilo("Pele","",1940); 
    assertEquals("From: Henkilo line: 61", "Pele", pele.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetSyntymavuosi72 */
  @Test
  public void testGetSyntymavuosi72() {    // Henkilo: 72
    Henkilo aku = new Henkilo("Aku","Ankka",1934); 
    assertEquals("From: Henkilo line: 74", 1934, aku.getSyntymavuosi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString84 */
  @Test
  public void testToString84() {    // Henkilo: 84
    Henkilo aku = new Henkilo("Aku","Ankka",1934); 
    assertEquals("From: Henkilo line: 86", "Aku|Ankka|1934", aku.toString()); 
    Henkilo pele = new Henkilo("Pele","",1940); 
    assertEquals("From: Henkilo line: 88", "Pele||1940", pele.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTulosta101 */
  @Test
  public void testTulosta101() {    // Henkilo: 101
    ByteArrayOutputStream byteoutput = new ByteArrayOutputStream(); 
    Henkilo hlo = new Henkilo("Aku","Ankka",1934); 
    hlo.tulosta(byteoutput); 
    { String _l_=byteoutput.toString(),_r_="Aku Ankka 1934\\s*"; if ( !_l_.matches(_r_) ) fail("From: Henkilo line: 106" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}
  } // Generated by ComTest END
}