package demo.d5.test;
// Generated by ComTest BEGIN
import java.io.*;
import static org.junit.Assert.*;
import org.junit.*;
import demo.d5.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.09 20:50:09 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LinjaAutoTest {



  // Generated by ComTest BEGIN
  /** testTulosta34 */
  @Test
  public void testTulosta34() {    // LinjaAuto: 34
    ByteArrayOutputStream byteoutput = new ByteArrayOutputStream(); 
    LinjaAuto linkki = new LinjaAuto(35); 
    linkki.tulosta(byteoutput); 
    { String _l_=byteoutput.toString(),_r_="Kapasiteetti: 35, matkustajia: 0, vapaita paikkoja: 35.\\s*"; if ( !_l_.matches(_r_) ) fail("From: LinjaAuto line: 39" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa72 */
  @Test
  public void testLisaa72() {    // LinjaAuto: 72
    LinjaAuto auto = new LinjaAuto(35); 
    auto.lisaa(5); 
    assertEquals("From: LinjaAuto line: 75", 30, auto.getTilaa()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVahenna94 */
  @Test
  public void testVahenna94() {    // LinjaAuto: 94
    LinjaAuto auto = new LinjaAuto(35); 
    auto.lisaa(5); 
    auto.vahenna(3); 
    assertEquals("From: LinjaAuto line: 98", 33, auto.getTilaa()); 
  } // Generated by ComTest END
}