package demo.d5.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import demo.d5.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.12 09:23:19 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ValiTest {



  // Generated by ComTest BEGIN
  /** testCompareTo86 */
  @Test
  public void testCompareTo86() {    // Vali: 86
    Vali vali1 = new Vali(1,3); 
    Vali vali2 = new Vali(2,4); 
    assertEquals("From: Vali line: 89", 0, vali1.compareTo(vali2)); 
    vali2.parse("3.5-"); 
    assertEquals("From: Vali line: 91", -1, vali1.compareTo(vali2)); 
    vali1.parse("5-10"); 
    assertEquals("From: Vali line: 93", 1, vali1.compareTo(vali2)); 
  } // Generated by ComTest END
}