package dynaaminenClone.test;
// Generated by ComTest BEGIN
import demo.d9.Int;
import static org.junit.Assert.*;
import org.junit.*;
import dynaaminenClone.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.17 13:40:21 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TaulukkoGenTest {



  // Generated by ComTest BEGIN
  /** 
   * testClone93 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone93() throws CloneNotSupportedException {    // TaulukkoGen: 93
    TaulukkoGen<Int> luvut = new TaulukkoGen<Int>(20); 
    luvut.lisaa(new Int(0)); luvut.lisaa(new Int(2)); 
    luvut.lisaa(new Int(99)); 
    TaulukkoGen<Int> taul = luvut.clone(); 
    assertEquals("From: TaulukkoGen line: 100", "0,2,99", luvut.toString()); 
    assertEquals("From: TaulukkoGen line: 101", "0,2,99", taul.toString()); 
    luvut.get(1).set(3); 
    assertEquals("From: TaulukkoGen line: 103", "0,3,99", luvut.toString()); 
    assertEquals("From: TaulukkoGen line: 104", "0,2,99", taul.toString()); 
    luvut.lisaa(new Int(2)); luvut.lisaa(new Int(5)); 
    luvut.lisaa(new Int(2)); luvut.lisaa(new Int(6)); 
    assertEquals("From: TaulukkoGen line: 107", "0,3,99,2,5,2,6", luvut.toString()); 
    assertEquals("From: TaulukkoGen line: 108", "0,2,99", taul.toString()); 
    try {
    assertEquals("From: TaulukkoGen line: 109", 2, taul.get(3).intValue()); 
    fail("TaulukkoGen: 109 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    luvut.poista(new Int(2)); 
    assertEquals("From: TaulukkoGen line: 111", "0,3,99,5,6", luvut.toString()); 
    assertEquals("From: TaulukkoGen line: 112", "0,2,99", taul.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista132 */
  @Test
  public void testPoista132() {    // TaulukkoGen: 132
    TaulukkoGen<Int> luvut = new TaulukkoGen<Int>(20); 
    luvut.lisaa(new Int(0)); luvut.lisaa(new Int(2)); luvut.lisaa(new Int(1)); luvut.lisaa(new Int(2)); 
    luvut.lisaa(new Int(3)); luvut.lisaa(new Int(4)); luvut.lisaa(new Int(1)); luvut.lisaa(new Int(2)); 
    assertEquals("From: TaulukkoGen line: 136", "0,2,1,2,3,4,1,2", luvut.toString()); 
    luvut.poista(new Int(0)); 
    assertEquals("From: TaulukkoGen line: 138", "2,1,2,3,4,1,2", luvut.toString()); 
    luvut.poista(new Int(4)); 
    assertEquals("From: TaulukkoGen line: 140", "2,1,2,3,1,2", luvut.toString()); 
    luvut.poista(new Int(2)); 
    assertEquals("From: TaulukkoGen line: 142", "1,3,1", luvut.toString()); 
    luvut.poista(new Int(2)); 
    assertEquals("From: TaulukkoGen line: 144", "1,3,1", luvut.toString()); 
    luvut.poista(new Int(1)); 
    assertEquals("From: TaulukkoGen line: 146", "3", luvut.toString()); 
    luvut.poista(new Int(3)); 
    assertEquals("From: TaulukkoGen line: 148", "", luvut.toString()); 
  } // Generated by ComTest END
}