package Pohja.Tauno.test;
// Generated by ComTest BEGIN
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import static Pohja.Tauno.Kasittele.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.05 19:34:37 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KasitteleTest {



  // Generated by ComTest BEGIN
  /** testKasitteleTaulukko33 */
  @Test
  public void testKasitteleTaulukko33() {    // Kasittele: 33
    int[] t; 
    t = new int[]{55, 44, 33, 2, 5, 9}; KasitteleTaulukko(t); assertEquals("From: Kasittele line: 39", "[9, 5, 2, 33, 44, 55]", Arrays.toString(t));  
    t = new int[]{23, 45, 12, 9, 3, 7}; KasitteleTaulukko(t); assertEquals("From: Kasittele line: 40", "[7, 3, 9, 12, 45, 23]", Arrays.toString(t));  
    t = new int[]{12, 9, 3, 7}; KasitteleTaulukko(t); assertEquals("From: Kasittele line: 41", "[7, 3, 9, 12]", Arrays.toString(t));  
    t = new int[]{3, 7}; KasitteleTaulukko(t); assertEquals("From: Kasittele line: 42", "[7, 3]", Arrays.toString(t));  
    t = new int[]{1}; KasitteleTaulukko(t); assertEquals("From: Kasittele line: 43", "[1]", Arrays.toString(t));  
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKasitteleTaulukkoaErilailla65 */
  @Test
  public void testKasitteleTaulukkoaErilailla65() {    // Kasittele: 65
    int[] t; 
    t = new int[]{55, 44, 33, 2, 5, 9}; KasitteleTaulukkoaErilailla(t); assertEquals("From: Kasittele line: 72", "[44, 55, 2, 33, 9, 5]", Arrays.toString(t));  
    t = new int[]{23, 45, 12, 9, 3, 7}; KasitteleTaulukkoaErilailla(t); assertEquals("From: Kasittele line: 73", "[45, 23, 9, 12, 7, 3]", Arrays.toString(t));  
    t = new int[]{12, 9, 3, 7}; KasitteleTaulukkoaErilailla(t); assertEquals("From: Kasittele line: 74", "[9, 12, 7, 3]", Arrays.toString(t));  
    t = new int[]{3, 7}; KasitteleTaulukkoaErilailla(t); assertEquals("From: Kasittele line: 75", "[7, 3]", Arrays.toString(t));  
    t = new int[]{1}; KasitteleTaulukkoaErilailla(t); assertEquals("From: Kasittele line: 76", "[1]", Arrays.toString(t));  
  } // Generated by ComTest END
}