package demo.d6.Astia.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import demo.d6.Astia.*;
// Generated by ComTest END
import fi.jyu.mit.ohj2.Suuntaaja;

/**
 * Test class made by ComTest
 * @version 2021.02.15 18:51:36 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AstiaPeliTest {



  // Generated by ComTest BEGIN
  /** testLisaa_astia73 */
  @Test
  public void testLisaa_astia73() {    // AstiaPeli: 73
    AstiaPeli peli = new AstiaPeli(); 
    peli.lisaa_astia("5",5); 
    assertEquals("From: AstiaPeli line: 76", "5", peli.anna(1).getNimi()); 
    peli.lisaa_astia("8",8); 
    assertEquals("From: AstiaPeli line: 78", "8", peli.anna(2).getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna94 */
  @Test
  public void testAnna94() {    // AstiaPeli: 94
    AstiaPeli peli = new AstiaPeli(); 
    peli.lisaa_astia("5",5); 
    peli.lisaa_astia("9",9); 
    assertEquals("From: AstiaPeli line: 98", "ä", peli.anna(0).getNimi()); 
    assertEquals("From: AstiaPeli line: 99", "5", peli.anna(1).getNimi()); 
    assertEquals("From: AstiaPeli line: 100", "9", peli.anna(2).getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsi113 */
  @Test
  public void testEtsi113() {    // AstiaPeli: 113
    AstiaPeli peli = new AstiaPeli(); 
    peli.lisaa_astia("5",5); 
    peli.lisaa_astia("8",8); 
    assertEquals("From: AstiaPeli line: 118", "ä", peli.etsi("ä").getNimi()); 
    assertEquals("From: AstiaPeli line: 119", "5", peli.etsi("5").getNimi()); 
    assertEquals("From: AstiaPeli line: 120", "8", peli.etsi("8").getNimi()); 
    try {
    assertEquals("From: AstiaPeli line: 121", "null", peli.etsi("6").getNimi()); 
    fail("AstiaPeli: 121 Did not throw NullPointerException");
    } catch(NullPointerException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTulosta_ohje167 */
  @Test
  public void testTulosta_ohje167() {    // AstiaPeli: 167
    Suuntaaja.StringOutput so = new Suuntaaja.StringOutput(); 
    AstiaPeli peli = new AstiaPeli(); 
    peli.lisaa_astia("5",5); 
    peli.lisaa_astia("8",8); 
    peli.tulosta_ohje(); 
    assertEquals("From: AstiaPeli line: 173", null, so.ero("Käytössäsi on 5.0 sekä 8.0 litran astiat ja Ämpari (100.0 l)\n")); 
    so.palauta(); 
  } // Generated by ComTest END
}