package demo.d7.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d7.Merkkijonot.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.22 14:21:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MerkkijonotTest {



  // Generated by ComTest BEGIN
  /** testPoistaLopusta83 */
  @Test
  public void testPoistaLopusta83() {    // Merkkijonot: 83
    StringBuilder sb = new StringBuilder("Testataan toimiiko"); 
    poistaLopusta(sb,5); 
    assertEquals("From: Merkkijonot line: 86", "Testataan toi", sb.toString()); 
    poistaLopusta(sb,4); 
    assertEquals("From: Merkkijonot line: 88", "Testataan", sb.toString()); 
    poistaLopusta(sb,0); 
    assertEquals("From: Merkkijonot line: 90", "Testataan", sb.toString()); 
    poistaLopusta(sb,-1); 
    assertEquals("From: Merkkijonot line: 92", "Testataan", sb.toString()); 
    poistaLopusta(sb,10); 
    assertEquals("From: Merkkijonot line: 94", "", sb.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaLopusta112 */
  @Test
  public void testPoistaLopusta112() {    // Merkkijonot: 112
    String s="Testataan toimiiko"; 
    assertEquals("From: Merkkijonot line: 114", "Testataan toi", s = poistaLopusta(s,5)); 
    assertEquals("From: Merkkijonot line: 115", "Testataan", s = poistaLopusta(s,4)); 
    assertEquals("From: Merkkijonot line: 116", "Testataan", s = poistaLopusta(s,0)); 
    assertEquals("From: Merkkijonot line: 117", "Testataan", s = poistaLopusta(s,-1)); 
    assertEquals("From: Merkkijonot line: 118", "", s = poistaLopusta(s,10)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testMerkkienMaara136 */
  @Test
  public void testMerkkienMaara136() {    // Merkkijonot: 136
    String jono = "Kissa istuu puussa"; 
    String merkit = "k"; 
    assertEquals("From: Merkkijonot line: 139", 1, merkkienMaara(jono, merkit)); 
    merkit = "a"; 
    assertEquals("From: Merkkijonot line: 141", 2, merkkienMaara(jono, merkit)); 
    merkit = "ak"; 
    assertEquals("From: Merkkijonot line: 143", 3, merkkienMaara(jono, merkit)); 
    merkit = "b-j"; 
    assertEquals("From: Merkkijonot line: 145", 2, merkkienMaara(jono, merkit)); 
    merkit = "a-jr-w"; 
    assertEquals("From: Merkkijonot line: 147", 14, merkkienMaara(jono, merkit)); 
    merkit = "a-jpr-w"; 
    assertEquals("From: Merkkijonot line: 149", 15, merkkienMaara(jono, merkit)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testOnkoSamat168 */
  @Test
  public void testOnkoSamat168() {    // Merkkijonot: 168
    String syote = "matti"; 
    String nimi ="Matti Nykänen"; 
    assertEquals("From: Merkkijonot line: 171", false, onkoSamat(syote, nimi)); 
    syote = "matti nykänen"; 
    assertEquals("From: Merkkijonot line: 173", true, onkoSamat(syote, nimi)); 
    syote = "matti*"; 
    assertEquals("From: Merkkijonot line: 175", true, onkoSamat(syote, nimi)); 
    syote = " mati* "; 
    assertEquals("From: Merkkijonot line: 177", false, onkoSamat(syote, nimi)); 
    syote = " atti* "; 
    assertEquals("From: Merkkijonot line: 179", false, onkoSamat(syote, nimi)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testOnkoJoku202 */
  @Test
  public void testOnkoJoku202() {    // Merkkijonot: 202
    String mj = "Testi"; 
    String kirjaimet = "a"; 
    assertEquals("From: Merkkijonot line: 205", false, onkoJoku(mj, kirjaimet)); 
    kirjaimet ="aS"; 
    assertEquals("From: Merkkijonot line: 207", false, onkoJoku(mj, kirjaimet)); 
    kirjaimet ="aSs"; 
    assertEquals("From: Merkkijonot line: 209", true, onkoJoku(mj, kirjaimet)); 
    kirjaimet =""; 
    assertEquals("From: Merkkijonot line: 211", false, onkoJoku(mj, kirjaimet)); 
    mj = ""; 
    kirjaimet ="a"; 
    assertEquals("From: Merkkijonot line: 214", false, onkoJoku(mj, kirjaimet)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testOnkoMuita230 */
  @Test
  public void testOnkoMuita230() {    // Merkkijonot: 230
    String testi = "Testi"; 
    String vertaa = "esi"; 
    assertEquals("From: Merkkijonot line: 233", true, onkoMuita(testi,vertaa)); 
    vertaa = "esti"; 
    assertEquals("From: Merkkijonot line: 235", true, onkoMuita(testi,vertaa)); 
    vertaa = "eTsti"; 
    assertEquals("From: Merkkijonot line: 237", false, onkoMuita(testi,vertaa)); 
    testi = "isopahasusi"; 
    vertaa = "isuahpo"; 
    assertEquals("From: Merkkijonot line: 240", false, onkoMuita(testi,vertaa)); 
    vertaa = ""; 
    assertEquals("From: Merkkijonot line: 242", true, onkoMuita(testi,vertaa)); 
    testi = ""; 
    vertaa = "a"; 
    assertEquals("From: Merkkijonot line: 245", false, onkoMuita(testi,vertaa)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testViimeinen262 */
  @Test
  public void testViimeinen262() {    // Merkkijonot: 262
    String mj = "Siiseli on mahtava"; 
    assertEquals("From: Merkkijonot line: 264", 6, viimeinen(mj, 'i')); 
    assertEquals("From: Merkkijonot line: 265", 5, viimeinen(mj, 'l')); 
    assertEquals("From: Merkkijonot line: 266", 3, viimeinen(mj, 's')); 
    assertEquals("From: Merkkijonot line: 267", 0, viimeinen(mj, 'S')); 
    assertEquals("From: Merkkijonot line: 268", 10, viimeinen(mj, ' ')); 
    assertEquals("From: Merkkijonot line: 269", -1, viimeinen(mj, 'T')); 
    mj = ""; 
    assertEquals("From: Merkkijonot line: 271", -1, viimeinen(mj, 'a')); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPalindromi284 */
  @Test
  public void testPalindromi284() {    // Merkkijonot: 284
    String sana = "abba"; 
    assertEquals("From: Merkkijonot line: 286", true, palindromi(sana)); 
    sana = "apua"; 
    assertEquals("From: Merkkijonot line: 288", false, palindromi(sana)); 
    sana = "saippuakauppias"; 
    assertEquals("From: Merkkijonot line: 290", true, palindromi(sana)); 
    sana = "Saippuakauppias"; 
    assertEquals("From: Merkkijonot line: 292", true, palindromi(sana)); 
  } // Generated by ComTest END
}