package demo.d7.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d7.Postimaksu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.17 20:38:59 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PostimaksuTest {



  // Generated by ComTest BEGIN
  /** testSuurinKirjeenPaino43 */
  @Test
  public void testSuurinKirjeenPaino43() {    // Postimaksu: 43
    assertEquals("From: Postimaksu line: 44", 0, suurinKirjeenPaino(0)); 
    assertEquals("From: Postimaksu line: 45", 0, suurinKirjeenPaino(0.5)); 
    assertEquals("From: Postimaksu line: 46", 50, suurinKirjeenPaino(1)); 
    assertEquals("From: Postimaksu line: 47", 50, suurinKirjeenPaino(1.39)); 
    assertEquals("From: Postimaksu line: 48", 100, suurinKirjeenPaino(1.40)); 
    assertEquals("From: Postimaksu line: 49", 250, suurinKirjeenPaino(2.20)); 
    assertEquals("From: Postimaksu line: 50", 500, suurinKirjeenPaino(4.00)); 
    assertEquals("From: Postimaksu line: 51", 1000, suurinKirjeenPaino(9.90)); 
    assertEquals("From: Postimaksu line: 52", 2000, suurinKirjeenPaino(10.10)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSuurinKirjeenPainoTaulukolla73 */
  @Test
  public void testSuurinKirjeenPainoTaulukolla73() {    // Postimaksu: 73
    assertEquals("From: Postimaksu line: 74", 0, suurinKirjeenPainoTaulukolla(0)); 
    assertEquals("From: Postimaksu line: 75", 0, suurinKirjeenPainoTaulukolla(0.5)); 
    assertEquals("From: Postimaksu line: 76", 50, suurinKirjeenPainoTaulukolla(1)); 
    assertEquals("From: Postimaksu line: 77", 50, suurinKirjeenPainoTaulukolla(1.39)); 
    assertEquals("From: Postimaksu line: 78", 100, suurinKirjeenPainoTaulukolla(1.40)); 
    assertEquals("From: Postimaksu line: 79", 250, suurinKirjeenPainoTaulukolla(2.20)); 
    assertEquals("From: Postimaksu line: 80", 500, suurinKirjeenPainoTaulukolla(4.00)); 
    assertEquals("From: Postimaksu line: 81", 1000, suurinKirjeenPainoTaulukolla(9.90)); 
    assertEquals("From: Postimaksu line: 82", 2000, suurinKirjeenPainoTaulukolla(10.10)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSuurinKirjeenPainoTaulukolla299 */
  @Test
  public void testSuurinKirjeenPainoTaulukolla299() {    // Postimaksu: 99
    assertEquals("From: Postimaksu line: 100", 0, suurinKirjeenPainoTaulukolla2(0)); 
    assertEquals("From: Postimaksu line: 101", 0, suurinKirjeenPainoTaulukolla2(0.5)); 
    assertEquals("From: Postimaksu line: 102", 50, suurinKirjeenPainoTaulukolla2(1)); 
    assertEquals("From: Postimaksu line: 103", 50, suurinKirjeenPainoTaulukolla2(1.39)); 
    assertEquals("From: Postimaksu line: 104", 100, suurinKirjeenPainoTaulukolla2(1.40)); 
    assertEquals("From: Postimaksu line: 105", 250, suurinKirjeenPainoTaulukolla2(2.20)); 
    assertEquals("From: Postimaksu line: 106", 500, suurinKirjeenPainoTaulukolla2(4.00)); 
    assertEquals("From: Postimaksu line: 107", 1000, suurinKirjeenPainoTaulukolla2(9.90)); 
    assertEquals("From: Postimaksu line: 108", 2000, suurinKirjeenPainoTaulukolla2(10.10)); 
  } // Generated by ComTest END
}