package demo.d7.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo.d7.Postimaksu2.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.02.17 20:45:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class Postimaksu2Test {



  // Generated by ComTest BEGIN
  /** testSuurinKirjeenPaino32 */
  @Test
  public void testSuurinKirjeenPaino32() {    // Postimaksu2: 32
    assertEquals("From: Postimaksu2 line: 33", 0, suurinKirjeenPaino(0)); 
    assertEquals("From: Postimaksu2 line: 34", 0, suurinKirjeenPaino(0.5)); 
    assertEquals("From: Postimaksu2 line: 35", 50, suurinKirjeenPaino(1)); 
    assertEquals("From: Postimaksu2 line: 36", 50, suurinKirjeenPaino(1.39)); 
    assertEquals("From: Postimaksu2 line: 37", 100, suurinKirjeenPaino(1.40)); 
    assertEquals("From: Postimaksu2 line: 38", 250, suurinKirjeenPaino(2.20)); 
    assertEquals("From: Postimaksu2 line: 39", 500, suurinKirjeenPaino(4.00)); 
    assertEquals("From: Postimaksu2 line: 40", 1000, suurinKirjeenPaino(9.90)); 
    assertEquals("From: Postimaksu2 line: 41", 2000, suurinKirjeenPaino(10.10)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSuurinKirjeenPainoTaulukolla62 */
  @Test
  public void testSuurinKirjeenPainoTaulukolla62() {    // Postimaksu2: 62
    assertEquals("From: Postimaksu2 line: 63", 0, suurinKirjeenPainoTaulukolla(0), 0.000001); 
    assertEquals("From: Postimaksu2 line: 64", 0, suurinKirjeenPainoTaulukolla(0.5), 0.000001); 
    assertEquals("From: Postimaksu2 line: 65", 50, suurinKirjeenPainoTaulukolla(1), 0.000001); 
    assertEquals("From: Postimaksu2 line: 66", 50, suurinKirjeenPainoTaulukolla(1.39), 0.000001); 
    assertEquals("From: Postimaksu2 line: 67", 100, suurinKirjeenPainoTaulukolla(1.40), 0.000001); 
    assertEquals("From: Postimaksu2 line: 68", 250, suurinKirjeenPainoTaulukolla(2.20), 0.000001); 
    assertEquals("From: Postimaksu2 line: 69", 500, suurinKirjeenPainoTaulukolla(4.00), 0.000001); 
    assertEquals("From: Postimaksu2 line: 70", 1000, suurinKirjeenPainoTaulukolla(9.90), 0.000001); 
    assertEquals("From: Postimaksu2 line: 71", 2000, suurinKirjeenPainoTaulukolla(10.10), 0.000001); 
  } // Generated by ComTest END
}